version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./interview_analysis.db
      - DEBUG=True
      # 配置Python pip使用阿里云镜像
      - PIP_INDEX_URL=https://mirrors.aliyun.com/pypi/simple/
      - PIP_TRUSTED_HOST=mirrors.aliyun.com
    volumes:
      - ./backend:/app
    networks:
      - interview-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      # 配置npm使用阿里云镜像
      - NPM_CONFIG_REGISTRY=https://registry.npmmirror.com
      - NPM_CONFIG_DISTURL=https://npmmirror.com/dist
    depends_on:
      - backend
    networks:
      - interview-network

networks:
  interview-network:
    driver: bridge
