version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./interview_analysis.db
      - DEBUG=True
    volumes:
      - ./backend:/app
    networks:
      - interview-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - interview-network

networks:
  interview-network:
    driver: bridge
